### ISSUE TITLE
List of 100 repo's stuck at the end

### ISSUE THREAD

**Issue by Remourz** [xm1k3/cent#22]
Hello i'm running the command  cent -p cent-nuclei-templates -k 

But its like stuck at the last one, or does it just take time to finalize?

**Comment by Remourz** [comment]
![image](https://user-images.githubusercontent.com/63682157/182947628-f1fcbba6-7c0d-4e96-b036-96cb22f3b7f1.png)


Its been like this for about 20mins

**Comment by xm1k3** [comment]
Hi, probably the problem is related to git clone timeout

some time ago i fixed this problem here https://github.com/xm1k3/cent/commit/d7f356ac2d52205e4810fd0576fb0d36fb80559b

i will spend some time to test and after i will publish the fix on prod.

Check also the repos on the cent config file, maybe some repos are no longer available.

**Comment by sbani** [comment]
@xm1k3 , why do you use a Git clone instead of the zip tarball download and unzip option?

Git has a lot of overhead. Zip downloading would be much faster.

**Comment by xm1k3** [comment]
Hi everyone, i just updated the repo with a timeout feature, this will fix your problem

Let me know @sbani
