### ISSUE TITLE
Explain this.

### ISSUE THREAD

**Issue by FarjaalAhmad** [xm1k3/cent#23]
Can you explain why tf "Precompiled Binary" is accessing this?

![image](https://user-images.githubusercontent.com/45895453/184531309-06cea493-1809-40fd-808a-7a28bee5dcef.png)

**Comment by xm1k3** [comment]
Hi, honestly i don't know the problem here related to burpsuite
Sorry

**Comment by FarjaalAhmad** [comment]
this seems some sort of backdoor :|

**Comment by antifob** [comment]
@FarjaalAhmad  From a cursory look, it seems you ran something like "cent -p $HOME".
Then, @xm1k3 , code at https://github.com/xm1k3/cent/blob/5b2165bd009118977fa30bf22847fb0d8a2865ee/pkg/jobs/jobs.go#L132 went on to scan unrelated files.

To be fair, the trouble of handling this issue is big enough just because someone can't use a dedicated directory to store templates.

**Comment by BlacAmDK** [comment]
duplicate of #4 .
It's a bug, and #8 fixed this, but the precompiled binary does not update.

So @xm1k3 may be need an update for precompiled binary? because This is a serious bug that deletes the user's private files.

**Comment by xm1k3** [comment]
@BlacAmDK yes, i will add a new release with the new changes

**Comment by xm1k3** [comment]
@BlacAmDK check this: https://github.com/xm1k3/cent/releases/tag/v1.0.1
